### ISSUE TITLE
why print_structured_result not support ttp 

### ISSUE THREAD

**Issue by JamLeeCode** [scrapli/nornir_scrapli#118]
RT

**Comment by carlmontanari** [comment]
Honest answer: I dont use nornir so I never considered adding it :)

I'd be open to a PR to add support for it but would need to consider how to support TTP since it would require a template file and I don't necessarily want to add another optional parameter, but we could definitely see what that would look like.

You can also always access the "normal" scrapli response object inside your nornir response object -- something like `response['some task'][0].scrapli_response` with that you can call the `ttp_parse_output` method of that.
