### ISSUE TITLE
 Fatal Python error: PyImport_GetModuleDict: no module dictionary!

### ISSUE THREAD

**Issue by mechkhans** [scrapli/nornir_scrapli#23]
Hello Carl, 

Running a script with nornir+scrapli manually works fine, but scheduling it via a cron-job on jenkins bombs out with following lines, stackoverflow is not helpful in determining what could cause this, would you please let me know if this is a known issue?

the only change in script is migrating over to scrapli from netmiko. the hosts file is a combination of telnet, and ssh connections.

```
Fatal Python error: PyImport_GetModuleDict: no module dictionary!

Current thread 0x00007f4ae4fb4740 (most recent call first):
  File "/usr/local/jenkins/workspace/.../.ve/lib/python3.6/site-packages/scrapli/transport/ptyprocess.py", line 355 in close
  File "/usr/local/jenkins/.../.ve/lib/python3.6/site-packages/scrapli/transport/ptyprocess.py", line 335 in __del__
/usr/local/jenkins/.../durable-a4d75dd3/script.sh: line 1:  6340 Aborted                 ./.ve/bin/python nornir.py
```

sample repo can be found here: https://github.com/mechkhans/nornir_save_and_backup/

thanks,
-muddasir

**Comment by carlmontanari** [comment]
Looks like [this](https://bugs.python.org/issue26153) may be related.

I would say try 3.7+ and/or close the connection(s) explicitly rather than leaving things open and letting things close when nornir/script is done. This does not look like anything that would cause me to add a fix in scrapli as it seems pretty specific (and realistically I will probably call 3.6 support "unofficial" once 3.10 comes out probably).

Let us know if 3.7 or closing things manually helps!

Carl

**Comment by mechkhans** [comment]
after fighting a bit with the jenkins pipeline syntax this works as expected in py38. :-) 

thank you!

**Comment by carlmontanari** [comment]
Awesome, glad to hear it @mechkhans!!
